### ISSUE TITLE
How to set custom application properties when sending a message

### ISSUE THREAD

**Issue by AhyaanTech** [minghuaw/azservicebus#27]
https://docs.rs/azservicebus/latest/azservicebus/primitives/service_bus_message/struct.ServiceBusMessage.html#method.application_properties

i read that and i think that doesnt give us an api to update the application properties? or should we create a raw amqp message for it?

**Comment by minghuaw** [comment]
Added the mut getter in #29

**Comment by minghuaw** [comment]
> I also need to do this- do you have an example of how to use `application_properties_mut` to set a key-value pair? 

Something like this should do

```rust
let mut message = ServiceBusMessage::new(format!("Message {}", i));

message.application_properties_mut()
    .get_or_insert(ApplicationProperties::default())
    .insert(String::from("key"), SimpleValue::from("value"));
```

> It looks like the `SimpleValue` I need to set might be private?

The `SimpleValue` type isn't private. You might need to import a new dep [`fe2o3-amqp-types`](https://docs.rs/fe2o3-amqp-types/0.10.0/fe2o3_amqp_types/primitives/enum.SimpleValue.html). Please note that the version used in `azservicebus` is `"0.10"`

**Comment by brianmgray** [comment]
Thanks @minghuaw ! I'll give it a try

**Comment by AhyaanTech** [comment]
Tested and it works! Thank you @minghuaw

**Comment by brianmgray** [comment]
Yep this works, thank you @minghuaw !
