### ISSUE TITLE
How to list all the queues or topics that exist for a service bus entity?

### ISSUE THREAD

**Issue by jawadkalia** [minghuaw/azservicebus#9]
https://learn.microsoft.com/en-us/rest/api/servicebus/enumeration

How to perform that operation using this library?

**Comment by minghuaw** [comment]
This is a management API that uses a HTTP request. The crate as of now only implements the AMQP side of the SDK, and thus this operation is not supported by the crate. However, since it is a HTTP request, it should be fairly straightforward to implement it using the `reqwest` crate.

**Comment by jawadkalia** [comment]
Thank you so much!

Would you be adding http capabilities in this crate in the future?

**Comment by minghuaw** [comment]
> Thank you so much!
> 
> Would you be adding http capabilities in this crate in the future?

I am planning to but don't have time currently. It will likely be part of #2
